spring:
  data:
    mongodb:
      host: localhost
      uri: mongodb+srv://chnadrakarnehil06112002:tHX31Vk3lzL4KQnm@cluster0.ty8x7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: JournalDb
      auto-index-creation: true
  application:
    name: journaling
  redis:
    uri: docker run -it --rm redis:alpine redis-cli -u redis://default:anEa1JxGSPA6H3aOxR4jd1XxIuAMSdXS@redis-10369.crce179.ap-south-1-1.ec2.redns.redis-cloud.com:10369
